export const STACK_WELCOME = "STACK_WELCOME";

export const SIGN_IN_TAB = "SIGN_IN_TAB";
export const SIGN_UP_TAB = "SIGN_UP_TAB";

export const TOKEN = "token";

// Error code.
export const ERROR_CODE_NOT_FOUND = "ERROR_CODE_NOT_FOUND";
export const ERROR_CODE_INCORRECT_PASSWORD = "ERROR_CODE_INCORRECT_PASSWORD";
export const ERROR_CODE_EMAIL_ALREADY_EXISTS =
  "ERROR_CODE_EMAIL_ALREADY_EXISTS";
export const ERROR_CODE_USERNAME_ALREADY_EXISTS =
  "ERROR_CODE_USERNAME_ALREADY_EXISTS";
